### ISSUE TITLE
איך משתמשים?

### ISSUE THREAD

**Issue by Kaki12356** [itay-nakash/InstegramBot#1]
היי איתי, אשמח אם תוכל להסביר איך משתמשים בבוט?

**Comment by itay-nakash** [comment]
היי,
אעדכן בגיט, האמת שזה פרויקט שבעיקר היה אוסף ניסויים, ולא באמת נגמר במוצר מוגמר..
הבוט יודע לטעון לפי האשטאג (שצריך להאכיל אותו דרך הקוד) או לפי שמות ספציפים שאפשר להקריא מרשימה, אבל בגלל שאינסטגרם מבצעים פיקוח יחסית חריף, וקל מאוד לשרוף בוטים(ולמחוק משתמשים על זה), לא השמשתי את הבוט באופן סופי למצב שאפשר להשתמש בו.
בגדול, יש פונקציות בסיסיות שנותנות רפרוש וטעינת משתמשים לפי האשטאג או שמות, אבל לא ברמה עצמאית לחלוטין.
מצטער אם זה היה לא ברור לגמרי, והשקעת זמן בלנסות להפעיל אותו אוטומטית,
בהצלחה 🙃
________________________________
מאת: arazi1111 <notifications@github.com>
‏‏נשלח: יום ראשון 31 ינואר 2021 19:30
‏‏אל: itay-nakash/InstegramBot <InstegramBot@noreply.github.com>
עותק: Subscribed <subscribed@noreply.github.com>
‏‏נושא: [itay-nakash/InstegramBot] איך משתמשים? (#1)


היי איתי, אשמח אם תוכל להסביר איך משתמשים בבוט?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fitay-nakash%2FInstegramBot%2Fissues%2F1&data=04%7C01%7Citay.nakash%40campus.technion.ac.il%7C2fa935fc9b654a48755e08d8c60df5c3%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637477111126873942%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LagRlX6LV2UeACbi%2Fv0oaCJUocziSWq9IGZ30yrsln0%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOUKVUFCKIC33NJOBTJULLTS4WHUXANCNFSM4W3RO46Q&data=04%7C01%7Citay.nakash%40campus.technion.ac.il%7C2fa935fc9b654a48755e08d8c60df5c3%7Cf1502c4cee2e411c9715c855f6753b84%7C1%7C0%7C637477111126883938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hrtnD4rGH5HkVSiFUyN4Kboxfd7v5MDPHGXF3uI1Dsc%3D&reserved=0>.

External e-mail, be judicious when opening attachments or links

**Comment by Kaki12356** [comment]
תודה רבה על התשובה המהירה :)

בתאריך יום א׳, 31 בינו׳ 2021, 19:42, מאת itay nakash ‏<
notifications@github.com>:

**Comment by itay-nakash** [comment]
בכיף,
אעדכן בקובץ כדי לחסוך זמן לאחרים, אבל תראה אולי תצליח להפיק ממה שיש שם קצת בכל זאת
בהצלחה!
